package com.gearline.domain.audit;

public enum AuditEventType {
    // Product
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_ARCHIVED,

    // Listing
    LISTING_PUBLISHED,
    LISTING_UPDATED,
    LISTING_DELISTED,
    LISTING_FAILED,

    // Inventory
    INVENTORY_SYNCED,
    INVENTORY_MISMATCH_DETECTED,
    INVENTORY_CORRECTED,

    // Order
    ORDER_IMPORTED,
    ORDER_STATUS_UPDATED,

    // Marketplace
    MARKETPLACE_CONNECTED,
    MARKETPLACE_DISCONNECTED,
    MARKETPLACE_AUTH_REFRESHED,
    MARKETPLACE_ERROR,

    // Webhooks
    WEBHOOK_RECEIVED,
    WEBHOOK_PROCESSING_FAILED,
    WEBHOOK_SIGNATURE_INVALID,

    // Sync jobs
    SYNC_JOB_STARTED,
    SYNC_JOB_COMPLETED,
    SYNC_JOB_FAILED,
    SYNC_JOB_DEAD_LETTERED,
    SYNC_JOB_REPLAYED,

    // Auth
    USER_LOGIN,
    USER_LOGOUT,
    USER_CREATED,
    TOKEN_REFRESHED
}
